export const ASSET_MAP: Record<string, string> = {
  // === ARTÉFACTS ===
  "ancien rituel royal": "UI_RelicIcon_15007_4",
  "colère de tonnerre": "UI_RelicIcon_15008_4",
  "dompteur de foudre": "UI_RelicIcon_15009_4",
  "ombre de la verte chasseuse": "UI_RelicIcon_15005_4",
  "amour chéri": "UI_RelicIcon_15004_4",
  "roche ancienne": "UI_RelicIcon_15014_4",
  "météore inversé": "UI_RelicIcon_15015_4",
  "sorcière des flammes ardentes": "UI_RelicIcon_15006_4",
  "marcheur du feu": "UI_RelicIcon_15010_4",
  "briseur de glace": "UI_RelicIcon_14001_4",
  "âme des profondeurs": "UI_RelicIcon_15016_4",
  "rideau du gladiateur": "UI_RelicIcon_15001_4",
  "bande vagabonde": "UI_RelicIcon_15003_4",
  "chevalerie ensanglantée": "UI_RelicIcon_15011_4",
  "ténacité du millelithe": "UI_RelicIcon_15017_4",
  "flamme blême": "UI_RelicIcon_15018_4",
  "réminiscence nostalgique": "UI_RelicIcon_15019_4",
  "emblème du destin brisé": "UI_RelicIcon_15020_4",
  "coquille des rêves opulents": "UI_RelicIcon_15021_4",
  "palourde aux teintes océaniques": "UI_RelicIcon_15022_4",
  "au-delà cinabrin": "UI_RelicIcon_15023_4",
  "échos d'une offrande": "UI_RelicIcon_15024_4",
  "souvenir de forêt": "UI_RelicIcon_15025_4",
  "rêve doré": "UI_RelicIcon_15026_4",
  "chronique du pavillon du désert": "UI_RelicIcon_15027_4",
  "fleur du paradis perdu": "UI_RelicIcon_15028_4",
  "rêve de la nymphe": "UI_RelicIcon_15029_4",
  "lueur du vourukasha": "UI_RelicIcon_15030_4",
  "chasseur de la maréchaussée": "UI_RelicIcon_15031_4",
  "troupe dorée": "UI_RelicIcon_15032_4",
  "murmure nocturne en forêt d'échos": "UI_RelicIcon_15033_4",
  "chanson des jours anciens": "UI_RelicIcon_15034_4",
  "fragment d'harmonie fantastique": "UI_RelicIcon_15035_4",
  "rêverie inachevée": "UI_RelicIcon_15036_4",
  "parchemin du héros de la cité cendrée": "UI_RelicIcon_15037_4",
  "codex de l'obsidienne secrète": "UI_RelicIcon_15038_4",

  // === ARMES 5 ÉTOILES ===
  "coupeur de jade primordial": "UI_EquipIcon_Sword_Morax",
  "reflet de tranche-brume": "UI_EquipIcon_Sword_Narukami",
  "serment de la liberté": "UI_EquipIcon_Sword_Widsith",
  "clé de khaj-nisut": "UI_EquipIcon_Sword_Deshret",
  "lumière d'incision foliaire": "UI_EquipIcon_Sword_Ayus",
  "splendeur des eaux paisibles": "UI_EquipIcon_Sword_Plaisir",
  "croc de l'obscurité": "UI_EquipIcon_Sword_Apep",
  "mort-du-loup": "UI_EquipIcon_Claymore_Wolfmound",
  "fierté de la voûte d'azur": "UI_EquipIcon_Claymore_Dvalin",
  "brise-pierre de cornes rouges": "UI_EquipIcon_Claymore_Itadorimaru",
  "balise de la mer de roseaux": "UI_EquipIcon_Claymore_Deshret",
  "bâton de homa": "UI_EquipIcon_Pole_Homa",
  "lance de jade ailée": "UI_EquipIcon_Pole_Morax",
  "lumière du faucheur": "UI_EquipIcon_Pole_Narukami",
  "étouffeur de calamités": "UI_EquipIcon_Pole_Santian",
  "bâton des sables écarlates": "UI_EquipIcon_Pole_Deshret",
  "simulacre de l'eau": "UI_EquipIcon_Bow_Kirin",
  "étoile polaire": "UI_EquipIcon_Bow_Worldbane",
  "l'ultime soupir": "UI_EquipIcon_Bow_Widsith",
  "pulsation du tonnerre": "UI_EquipIcon_Bow_Narukami",
  "première grande magie": "UI_EquipIcon_Bow_Plaisir",
  "tome du flux éternel": "UI_EquipIcon_Catalyst_Plaisir",
  "splendeur de l'azur": "UI_EquipIcon_Catalyst_Baizhu",
  "rêve flottant": "UI_EquipIcon_Catalyst_Ayus",
  "vérité de kagura": "UI_EquipIcon_Catalyst_Narukami",
  "l'origine des quatre vents": "UI_EquipIcon_Catalyst_Zephyrus",
  "atlas de la voûte d'azur": "UI_EquipIcon_Catalyst_Dvalin",

  // === ARMES 4 ÉTOILES ===
  "épée de favonius": "UI_EquipIcon_Sword_Zephyrus",
  "épée rituelle": "UI_EquipIcon_Sword_Fossil",
  "piqûre de fer": "UI_EquipIcon_Sword_Excalibur",
  "croc suppurant": "UI_EquipIcon_Sword_Magnum",
  "lame kageuchi d'amenoma": "UI_EquipIcon_Sword_Bakufu",
  "épée noire": "UI_EquipIcon_Sword_Bloodfell",
  "passeur du gué cendré": "UI_EquipIcon_Sword_Mechanic",
  "clair-obscur": "UI_EquipIcon_Sword_Macha",
  "espadon de favonius": "UI_EquipIcon_Claymore_Zephyrus",
  "espadon rituel": "UI_EquipIcon_Claymore_Fossil",
  "ossature du dragon": "UI_EquipIcon_Claymore_Kila",
  "ombre blanche": "UI_EquipIcon_Claymore_Excalibur",
  "la prise": "UI_EquipIcon_Pole_Mourn",
  "fléau du dragon": "UI_EquipIcon_Pole_Starmetal",
  "lance de favonius": "UI_EquipIcon_Pole_Zephyrus",
  "scion de la victoire": "UI_EquipIcon_Pole_Gladiator",
  "lance de rochenoire": "UI_EquipIcon_Pole_Blackrock",
  "arc de favonius": "UI_EquipIcon_Bow_Zephyrus",
  "arc rituel": "UI_EquipIcon_Bow_Fossil",
  "dernière corde": "UI_EquipIcon_Bow_Troupe",
  "arc de chasse verdoyant": "UI_EquipIcon_Bow_Fossil",
  "traqueur des impasses": "UI_EquipIcon_Bow_Magnum",
  "code de favonius": "UI_EquipIcon_Catalyst_Zephyrus",
  "mémoires de rituels": "UI_EquipIcon_Catalyst_Fossil",
  "mouvement vagabond": "UI_EquipIcon_Catalyst_Troupe",
  "prototype ambre": "UI_EquipIcon_Catalyst_Proto",
  "malice de malice": "UI_EquipIcon_Catalyst_Proto", // Synonyme
  "perle solaire": "UI_EquipIcon_Catalyst_Reshel",

  // === ARMES 3 ÉTOILES MÉTA ===
  "histoire des chasseurs de dragon": "UI_EquipIcon_Catalyst_Pulpfic",
  "pampille noire": "UI_EquipIcon_Pole_Halberd",
  "pampille blanche": "UI_EquipIcon_Pole_Tassel",
  "messager de l'aube": "UI_EquipIcon_Sword_Dawn",
  "guide de magie": "UI_EquipIcon_Catalyst_Intro",
  "lance-pierres": "UI_EquipIcon_Bow_Sling",
  "épée de la raison": "UI_EquipIcon_Claymore_Reason"
};

export const LOADING_PHRASES = [
  "Analyse des résonances élémentaires...",
  "Calcul du DPS...",
  "Recherche de synergies...",
  "Optimisation des rotations...",
  "Consultation des archives de Teyvat...",
  "Vérification des sets d'artefacts...",
];
